# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('birth', models.DateField(blank=True, verbose_name='Birthday')),
                ('age', models.PositiveSmallIntegerField(blank=True, verbose_name='Age')),
                ('height', models.PositiveSmallIntegerField(blank=True, default='', verbose_name='Height')),
                ('cup', models.CharField(blank=True, default='', max_length=1, verbose_name='Cup')),
                ('bust', models.PositiveSmallIntegerField(blank=True, default='', verbose_name='Bust')),
                ('waist', models.PositiveSmallIntegerField(blank=True, default='', verbose_name='Waist circumference')),
                ('hips', models.PositiveSmallIntegerField(blank=True, default='', verbose_name='Hips')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Place Of Birth')),
                ('hoby', models.CharField(blank=True, max_length=200, verbose_name='Hobbies')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created', 'name'),
            },
        ),
    ]
