# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='actress',
            name='bust',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Bust'),
        ),
        migrations.AlterField(
            model_name='actress',
            name='cup',
            field=models.CharField(blank=True, default='0', max_length=1, verbose_name='Cup'),
        ),
        migrations.AlterField(
            model_name='actress',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='actress',
            name='hips',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Hips'),
        ),
        migrations.AlterField(
            model_name='actress',
            name='waist',
            field=models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Waist circumference'),
        ),
    ]
