# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooAPI', '0003_auto_20161023_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birthday'),
        ),
    ]
