# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooAPI', '0005_auto_20161023_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actress',
            options={'ordering': ('uuid', 'created', 'name')},
        ),
        migrations.AddField(
            model_name='actress',
            name='uuid',
            field=models.CharField(default='-1', max_length=100),
        ),
    ]
