# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baikeApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiushi',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qiushi',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qiushi',
            name='image',
            field=models.TextField(),
        ),
    ]
